# Generated by Django 4.2.18 on 2025-02-11 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pessoa',
        ),
    ]
